x-bbot-server-base: &bbot-server-base
  build:
    context: .
  restart: always
  volumes:
    - ~/.config/bbot_server:/root/.config/bbot_server
    - ./bbot_server/defaults_docker.yml:/app/bbot_server/defaults.yml
    - .:/app

services:
  server:
    <<: *bbot-server-base
    ports:
      - "8807:8807"
    environment:
      - BBOT_HOST
      - BBOT_PORT
    command: ["bbctl", "server", "start", "--api-only", "--listen", "0.0.0.0"]

  watchdog:
    <<: *bbot-server-base
    command: ["bbctl", "server", "start", "--watchdog-only"]

  agent:
    <<: *bbot-server-base
    command: ["bbctl", "agent", "start"]
    volumes:
      - ./bbot_server/default_agent.sh:/app/bbot_server/default_agent.sh
    entrypoint: ["bash", "/app/bbot_server/default_agent.sh"]

  mongodb:
    image: mongo:latest
    restart: always
    # volumes:
    #   - ./mongodb:/data/db

  redis:
    image: redis:latest
    restart: always
