services:
  bbot-server:
    <<: *bbot-server-base
    ports:
      - "8807:8807"
    environment:
      - BBOT_HOST=0.0.0.0
      - BBOT_PORT=8807
      - BBOT_AUTO_RELOAD
    command: ["uvicorn", "bbot_server.api.app:server_app", "--host", "${BBOT_HOST}", "--port", "${BBOT_PORT}"]

  bbot-server-watchdog:
    <<: *bbot-server-base
    command: ["bbctl", "server", "start", "--watchdog-only"]

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb:/data/db

  nats:
    image: nats
    restart: always

x-bbot-server-base: &bbot-server-base
  build:
    context: .
  restart: always
  volumes:
    - ~/.config/bbot_server:/root/.config/bbot_server
    - ./bbot_server/defaults_docker.yml:/app/bbot_server/defaults.yml
    - .:/app
