services:
  bbot-server:
    build:
      context: .
    volumes:
      - ~/.config/bbot_server:/root/.config/bbot_server
      - .:/app
    ports:
      - "8807:8807"
    environment:
      - BBOT_PORT
      - BBOT_HOST
      - BBOT_AUTO_RELOAD
    command: bbot-server

  mongodb:
    image: mongo:latest

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
