services:
  bbot-server:
    build:
      context: .
    volumes:
      - ~/.config/bbot_server:/root/.config/bbot_server
      - ./bbot_server/defaults_docker.yml:/app/bbot_server/defaults.yml
      - .:/app
    ports:
      - "8807:8807"
    environment:
      - BBOT_PORT
      - BBOT_HOST
      - BBOT_AUTO_RELOAD

  mongodb:
    image: mongo:latest
    volumes:
      - ./mongodb:/data/db

  nats:
    image: nats
