name: tests
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v4
      - name: Setup NATS with JetStream
        run: |
          sudo apt-get update
          sudo apt-get install -y nats-server
          # Start NATS with JetStream enabled in the background
          nats-server --jetstream > nats.log 2>&1 &
          # Wait for NATS to be ready with timeout
          timeout=10
          until nats stream list || [ $timeout -eq 0 ]; do
            sleep .1
            ((timeout--))
          done
          if [ $timeout -eq 0 ]; then
            cat nats.log
            exit 1
          fi
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Lint
        run: |
          poetry run ruff check
          poetry run ruff format --check
      - name: Run tests
        run: |
          poetry run pytest --exitfirst --disable-warnings --log-cli-level=INFO --cov-report xml:cov.xml --cov=bbot_server .
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cov.xml
          verbose: true
