name: tests
on:
  push:
    branches:
      - stable
      - dev
  pull_request:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    uses: blacklanternsecurity/CLA/.github/workflows/python-tests.yml@883bfbc89464cadbeb10307b2b82891ba7853f56 # feat/shared-workflows
    secrets: inherit
    with:
      uv-sync-args: ""
      setup-script: tests/ci/services.sh
      pytest-args: --reruns 2 --disable-warnings --log-cli-level=INFO --cov-report xml:cov.xml --cov=bbot_server .
      env: '{"NO_COLOR": "true"}'
      coverage: true
